local src_dir = "$(projectdir)/libca.em/src/em_motion"

target("test-kin_diff")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "kin_diff.c"), "test_kin_diff.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-kin_omni")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "kin_omni.c"), "test_kin_omni.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-kin_mecanum")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "kin_mecanum.c"), "test_kin_mecanum.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-kin_ackermann")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "kin_ackermann.c"), "test_kin_ackermann.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-trapezoidal")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "trapezoidal.c"), "test_trapezoidal.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-s_curve")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "s_curve.c"), "test_s_curve.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-polynomial")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "polynomial.c"), "test_polynomial.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-inverted_pendulum")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "inverted_pendulum.c"), "test_inverted_pendulum.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-model_trajectory")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "model_trajectory.c"))
    add_files(path.join(src_dir, "trapezoidal.c"))
    add_files(path.join(src_dir, "s_curve.c"))
    add_files("test_model_trajectory.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-pwm_ptz")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "pwm_ptz.c"), "test_pwm_ptz.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")
