add_includedirs("$(projectdir)/src", { public = true })

includes("../src/em_base")
includes("../src/em_bus")
includes("../src/em_component")
includes("../src/em_crypto")
includes("../src/em_driver")
includes("../src/em_dstream")
includes("../src/em_eimui")
includes("../src/em_format")
includes("../src/em_log")
includes("../src/em_motion")
includes("../src/em_mpool")
includes("../src/em_ota")
includes("../src/em_platform")
includes("../src/em_protocol")
includes("../src/em_shell")
includes("../src/em_test")
includes("../src/em_util")

includes("tests")