local src_dir = "$(projectdir)/libca.em/src/em_dstream"

target("test-ring_buffer")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "ring_buffer.c"))
    add_files("test_ring_buffer.c", "test_ds_ring_buffer.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-fixed_buffer")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "fixed_buffer.c"), path.join(src_dir, "ds_fixed_buffer.c"))
    add_files("test_fixed_buffer.c", "test_ds_fixed_buffer.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-pingpong_buffer")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "pingpong_buffer.c"), "test_pingpong_buffer.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-delimiter_parser")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "delimiter_parser.c"), "test_delimiter_parser.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-length_parser")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "length_parser.c"), "test_length_parser.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")
