local src_dir = "$(projectdir)/src/em_util"

target("test-crc")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "crc.c"), "test_crc.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-endian_util")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "endian_util.c"), "test_endian_util.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-pid")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "pid.c"), "test_pid.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-filter")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "filter.c"), "test_filter.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-doubly_linked_list")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "doubly_linked_list.c"), "test_doubly_linked_list.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-queue")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "queue.c"), "test_queue.c")
    add_files(path.join(src_dir, "doubly_linked_list.c"))
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-stack")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "stack.c"), "test_stack.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-singly_list")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "singly_list.c"), "test_singly_list.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-lifo")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "lifo.c"), "test_lifo.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-doubly_list")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "doubly_list.c"), "test_doubly_list.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-mem_view")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "mem_view.c"), "test_mem_view.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")
