local src_dir = "$(projectdir)/src/em_format"

target("test-format")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "format.c"), "test_format.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-format-float-fixed")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "format.c"), "test_format.c")
    add_defines("FMT_ENABLE_FLOAT=1")
    add_defines("FMT_ENABLE_WIDTH_PRECISION=1")
    add_defines("FMT_ENABLE_HEX=1")
    add_defines("FMT_FLOAT_MODE=FMT_FLOAT_MODE_FIXED")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-format-float-simple")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "format.c"), "test_format.c")
    add_defines("FMT_ENABLE_FLOAT=1")
    add_defines("FMT_ENABLE_WIDTH_PRECISION=1")
    add_defines("FMT_ENABLE_HEX=1")
    add_defines("FMT_FLOAT_MODE=FMT_FLOAT_MODE_SIMPLE")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-format-float-normal")
    set_kind("binary")
    add_includedirs(src_dir, ".")
    add_files(path.join(src_dir, "format.c"), "test_format.c")
    add_defines("FMT_ENABLE_FLOAT=1")
    add_defines("FMT_ENABLE_WIDTH_PRECISION=1")
    add_defines("FMT_ENABLE_HEX=1")
    add_defines("FMT_FLOAT_MODE=FMT_FLOAT_MODE_NORMAL")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")
