target("em_shell")
    set_kind("object")
    set_group("em")
    add_files("shell.c")
    add_deps("em_base")

target("em_shell_static")
    set_kind("static")
    set_group("em")
    add_files("shell.c")
    add_deps("em_base")

target("shell_example")
    set_kind("binary")
    set_group("example")
    add_files("example.c")
    add_deps("em_shell")
