target("libca.em_format")
    set_kind("object")
    set_group("em")
    add_files("format.c")
    add_deps("libca.em_base")

target("libca.em_format_static")
    set_kind("static")
    set_group("em")
    add_files("format.c")
    add_deps("libca.em_base")
